<a href="https://colab.research.google.com/github/jindaldisha/Deep-Learning-and-Neural-Networks/blob/main/Neural-Networks-with-Tensorflow/00_2_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Basics

In [1]:
#Import Libraries
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array.

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [4]:
#Create a constant
t1 = torch.tensor(4.)
t1

tensor(4.)

In [6]:
#Check type and shape of a tensor
t1.dtype, t1.shape

(torch.float32, torch.Size([]))

In [7]:
#Create a 1D tensor
t2 = torch.tensor([1,2,3,4])
t2, t2.dtype, t2.shape

(tensor([1, 2, 3, 4]), torch.int64, torch.Size([4]))

In [9]:
#Create a 2D tensor
t3 = torch.tensor([[1.,2,3],[4,5,6],[7,8,9]])
t3, t3.dtype, t3.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.float32, torch.Size([3, 3]))

In [12]:
#Create a 3D tensor
t4 = torch.tensor([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                   [10,11,12]]])
t4, t4.dtype, t4.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]), torch.int64, torch.Size([2, 2, 3]))

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. 

In [13]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad = True)

In [14]:
#Arithmetic Operation
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In PyTorch, we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result y.

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [15]:
#Compute Derivative
y.backward()

In [17]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


We get a derivative of y w.r.t w and b because we set the `requires_grad = True` for them when creating the tensor but we didn't do it for x and the by defaut value of requires_grad is False.

The "grad" is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. 

In [18]:
#Create a tensor full of a single value
t5 = torch.full((3,3), 15)
t5

In [21]:
#Concatinate two tensor of compatible shapes
t6 = torch.cat((t5,t3))
t6, t6.shape

(tensor([[15., 15., 15.],
         [15., 15., 15.],
         [15., 15., 15.],
         [ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]]), torch.Size([6, 3]))

In [23]:
# Compute sine of each element
t7 = torch.sin(t6)
t7

tensor([[ 0.6503,  0.6503,  0.6503],
        [ 0.6503,  0.6503,  0.6503],
        [ 0.6503,  0.6503,  0.6503],
        [ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121]])

In [25]:
#Reshape a tensor
t8 = t7.reshape(3,3,2)
t8

tensor([[[ 0.6503,  0.6503],
         [ 0.6503,  0.6503],
         [ 0.6503,  0.6503]],

        [[ 0.6503,  0.6503],
         [ 0.6503,  0.8415],
         [ 0.9093,  0.1411]],

        [[-0.7568, -0.9589],
         [-0.2794,  0.6570],
         [ 0.9894,  0.4121]]])

##Interoperability with Numpy

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

The interoperability between PyTorch and Numpy is essential because most datasets are likely be read and preprocessed as Numpy arrays.

Even though Numpy already provides data structures and utilities for working with multi-dimensional numeric data, there are two main reasons why we need PyTorch:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

In [27]:
#Import Numpy
import numpy as np

In [33]:
x = np.array([[1,2],[3,4]])
x, x.dtype, type(x)

(array([[1, 2],
        [3, 4]]), dtype('int64'), numpy.ndarray)

In [34]:
#Convert numpy array to a torch tensor
y = torch.from_numpy(x)
y, y.dtype, type(y)

(tensor([[1, 2],
         [3, 4]]), torch.int64, torch.Tensor)

In [37]:
#Convert a torch tensor to numpy array
z = y.numpy()
z, z.dtype, type(z)

(array([[1, 2],
        [3, 4]]), dtype('int64'), numpy.ndarray)