<a href="https://colab.research.google.com/github/jindaldisha/Neural-Networks-with-Tensorflow/blob/main/00_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorflow Basics

Cover the fundamentals of tensor using tensorflow


In [ ]:
import tensorflow as tf
import sys
import numpy as np
import tensorflow_probability as tfp
print(tf.__version__)

2.5.0


In [ ]:
#Creating tensor with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([[10, 10]])
vector, vector.ndim

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10, 10]], dtype=int32)>,
 2)

In [ ]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [ ]:
#Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

A scalar had no shape and 0 dimensions, it is a single number

A vector has one dimension and a shape of (m,1) or (1,m)

A matrix has two dimensions and a shape of (m,n)

A tensor is an n-dimensional array of numbers

In [ ]:
#specify datatype
mat2 = tf.constant([[10. , 7.],
                    [2. , 3. ]], dtype=tf.float16)
mat2, mat2.ndim

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 2.,  3.]], dtype=float16)>, 2)

In [ ]:
mat3 = tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]]])
mat3, mat3.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>, 3)

In [ ]:
#Creating tensors with tf.variable
cons_tensor = tf.constant([10,7]) #unchangable
var_tensor = tf.Variable([10,7]) #changable

In [ ]:
cons_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
var_tensor[0] = 7

TypeError: ignored

In [ ]:
cons_tensor[0] = 7

TypeError: ignored

In [ ]:
var_tensor[0].assign(7)
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

We cannot change the values of constant tensors but we can change the values of variable tensors so we should choose accordingly

Creating random tensors

Random tensors are tensors of some arbitrary size which contains some random numbers

They are pseudo random numbers as we've set a seed here

In [ ]:
random1 = tf.random.Generator.from_seed(42) #set seed reproducibility
random1 = random1.normal(shape=(3,2))

In [ ]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

A uniform distribution sometimes known as a rectangular distribution is a distribution that has a constant probability

In [ ]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

In [ ]:
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#Shuffle the order of elements in a tensor
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>, 2)

We shuffle the order of elements in a tensor because it is valuable when you want to shuffle your data so that the inherent order of the data doesnt affect the way our model learns and then affects the final output that we get


In [ ]:
#shuffle a tensor along its first dimension
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
  #There are two seeds initializations because we need a global and operation level seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.zeros((2,3)), tf.ones((4,3))

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

The main difference between Tensorflow tensors and numpy arrays is that tensors can be run on gpu (much faster numeric computation)





Matrices and tensors are often represented with capital letters and vectors with small letter

In [ ]:
#Turn numpy arrays into tensors
numpy_A = np.arange(1,25, dtype=np.int32).reshape((2,3,4))
numpy_A

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
B = tf.Variable(numpy_A)

In [ ]:
B

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Getting information from tensors
* shape    tensor.shape
* Rank    tensor.ndim 
* Axis or dimension    tensor[0], tensor[:, 1]
* Size    tf.size(tensor)

In [ ]:
   B[:,1]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]], dtype=int32)>

In [ ]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
x = tf.zeros((2,3,4))
x


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
x.shape, x.ndim

(TensorShape([2, 3, 4]), 3)

In [ ]:
x[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
x[:-1, :-1, :-1]

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
B

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix2 = matrix
matrix2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix3 = matrix2[..., tf.newaxis]
matrix3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(matrix2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
tf.expand_dims(matrix2, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 7, 10]]], dtype=int32)>

In [ ]:
#Manipulating Tensors (Tensor Operations)
#Basic Operations +, -, *, / (Element Wise)

tensor = tf.constant([[10, 7],[3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

In [ ]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
#We can use built in functions too
#Built in functions are faster
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix Multiplication 

In machine learning, matrix multiplication is one the most common tensor operations

Matrix Multiplication is also referred to as the dot product.

You can do it using 
* tf.matmul()
* tf.tensordot()

or the python way of doing it using @ operator. though the tensor built in functions are faster

In [ ]:
mat1 = tf.constant([[1,2,7],
                    [7,2,1],
                    [3,3,3]])
mat2 = tf.constant([[2,5],
                    [6,7],
                    [1,8]])
mat1, mat2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
#Matrix Multiplication in tensorflow
%%time
tf.matmul(mat1, mat2)


CPU times: user 1.18 ms, sys: 11 µs, total: 1.2 ms
Wall time: 1.21 ms


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 75],
       [27, 57],
       [27, 60]], dtype=int32)>

In [ ]:
#Matrix Multiplication in python
%%time
mat1 @ mat2

CPU times: user 301 µs, sys: 0 ns, total: 301 µs
Wall time: 319 µs


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 75],
       [27, 57],
       [27, 60]], dtype=int32)>

In [ ]:
mat3 = tf.constant([[1,2,5],
                    [7,2,1],
                    [3,3,3]])
mat4 = tf.constant([[3,5],
                    [6,7],
                    [1,8]])
mat3, mat4

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
 tf.matmul(mat3, mat4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tf.matmul(mat4, mat3, transpose_a=True)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(mat4), mat3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

In [ ]:
 sales = tf.constant([[13,9,7,15],
                     [8,7,4,6],
                     [6,4,0,3]])
 cost = tf.constant([[3,4,2]])
 sales, cost

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[13,  9,  7, 15],
        [ 8,  7,  4,  6],
        [ 6,  4,  0,  3]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 4, 2]], dtype=int32)>)

In [ ]:
tf.matmul(cost, sales)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[83, 63, 37, 75]], dtype=int32)>

In [ ]:
tf.tensordot(cost, sales, axes=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[83, 63, 37, 75]], dtype=int32)>

In [ ]:
 #Changing the datatype of a tensor
 #It reduces the space our tensor takes on memory
 #This makes calculations faster
B = tf.constant([2.3,1.3], dtype=tf.float16)
A = tf.constant([1,2])
B, A


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.3, 1.3], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [ ]:
tf.cast(A, dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>

In [ ]:
tf.cast(A, dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

Aggregrate 

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

* absolute
* maximum
* minimum
* mean
* sum



In [ ]:
#Getting the absolute value
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
  sales

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[13,  9,  7, 15],
       [ 8,  7,  4,  6],
       [ 6,  4,  0,  3]], dtype=int32)>

In [ ]:
tf.reduce_max(sales), tf.reduce_min(sales), tf.reduce_mean(sales), tf.reduce_sum(sales)

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=82>)

In [ ]:
sum(sum(sales)), sum(sum(sales))/tf.size(sales)

(<tf.Tensor: shape=(), dtype=int32, numpy=82>,
 <tf.Tensor: shape=(), dtype=float64, numpy=6.833333333333333>)

In [ ]:
e = tf.constant(np.random.randint(100, size = 50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([20,  2, 97,  9, 23, 16,  0, 30, 48, 14, 60,  6, 75, 92, 80, 68,  1,
       85, 77, 13, 71, 90, 50, 60, 36, 84, 99, 49, 52, 61, 60, 74, 54, 94,
       42, 41, 50, 69,  9, 88, 88, 62,  5,  8, 34, 17, 48, 91, 60, 94])>

In [ ]:
tf.size(e), e.ndim, e.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [ ]:
tf.reduce_max(e), tf.reduce_min(e), tf.reduce_mean(tf.cast(e, dtype=tf.float32)), tf.reduce_sum(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=51.12>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2556>)

In [ ]:
#To find variance, we need to import tensorflow probability librar

In [ ]:
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=944>

In [ ]:
#Or we can also find it as follows
tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=944.22565>

In [ ]:
#data type needs to be real number (float)
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.728254>

In [ ]:
sales


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[13,  9,  7, 15],
       [ 8,  7,  4,  6],
       [ 6,  4,  0,  3]], dtype=int32)>

In [ ]:
tf.argmax(sales, axis = 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 0, 0])>

In [ ]:
tf.argmin(sales)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 2, 2])>

In [ ]:
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the position of the maximum and minimum
tf.argmax(f), tf.argmin(f)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [ ]:
f[tf.argmax(f)], f[tf.argmin(f)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
tf.reduce_max(f), tf.reduce_min(f)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
#Squezzing a tensor (removing all single dimensions)
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g_squeezed = tf.squeeze(g, [0,1,2])
g_squeezed

<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
      dtype=float32)>

One-hot encoding tensors

It is a form of numerical encoding

In [ ]:
h = [0, 1, 1, 3] #could be red, green, blue, purple

#One-hot encoding our list
tf.one_hot(h, depth=4, axis = 0)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
 #Specify custom values
tf.one_hot(h,depth=4, on_value="X", off_value="O")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'X', b'O', b'O', b'O'],
       [b'O', b'X', b'O', b'O'],
       [b'O', b'O', b'X', b'O'],
       [b'O', b'O', b'O', b'X']], dtype=object)>

In [ ]:
sales = tf.cast(sales, dtype=tf.float32)
sales

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[13.,  9.,  7., 15.],
       [ 8.,  7.,  4.,  6.],
       [ 6.,  4.,  0.,  3.]], dtype=float32)>

In [ ]:
tf.sqrt(sales)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[3.6055508, 2.9999998, 2.6457512, 3.8729832],
       [2.8284268, 2.6457512, 1.9999999, 2.4494896],
       [2.4494898, 2.       , 0.       , 1.7320508]], dtype=float32)>

In [ ]:
tf.square(sales)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[169.,  81.,  49., 225.],
       [ 64.,  49.,  16.,  36.],
       [ 36.,  16.,   0.,   9.]], dtype=float32)>

In [ ]:
tf.math.log(sales)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2.5649493, 2.1972246, 1.9459102, 2.7080503],
       [2.0794415, 1.9459102, 1.3862944, 1.7917595],
       [1.7917595, 1.3862944,      -inf, 1.0986123]], dtype=float32)>

Numpy is the fundamental package for any type of numerical and scientific computing with Python

Tensorflow is built upon tensors

Numpy is built upon the numpy array


We do this conversion when some functionability doesnt work with tensors but works with numpy, turning the tensor into the numpy array enables us to access it and vice a versa


Numpy arrays create a dtype of float64

Tensor are of default type of float32 

In [ ]:
  #Convert numpy array to tensor
 j = tf.constant(np.array([[2.,7.,9.]]))
 j


<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[2., 7., 9.]])>

In [ ]:
#Convert tensor to numpy array
np.array(j), type(np.array(j))

(array([[2., 7., 9.]]), numpy.ndarray)

In [ ]:
  j.numpy(), type(j.numpy())

(array([[2., 7., 9.]]), numpy.ndarray)

In [ ]:
numpy_j = tf.constant(np.array([[2.,7.,9.]]))
tensor_j = tf.constant([[2.,7.,9.]])
numpy_j, tensor_j

(<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[2., 7., 9.]])>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2., 7., 9.]], dtype=float32)>)

TPU (Tensor Processing Unit) is a AI acclerator application-specific integrated circuit developed by Google specifically for neural network, machine learning, particularly using google's own tensorflow software.


GPUs and TPUs are much faster than CPUs

In [ ]:
import tensorflow as tf

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
#To check the type of GPU
!nvidia-smi

Wed Jun 16 16:02:16 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Since we're using colab, we will automatically have a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible.
